# .github/workflows/quality-checks.yml
name: Quality Checks
on:
  pull_request:
    types: [edited, opened, synchronize, reopened]

jobs:
  commit-message:
    name: Conventional Commit Message Compliance
    runs-on: ubuntu-latest

    steps:
      - name: Run Commisery
        uses: tomtom-international/commisery-action@v2
        with:
          token: ${{ github.token }}

  lint:
    name: Coding Standards Compliance
    runs-on: ubuntu-latest

    steps:
      - name: Check-out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dev dependencies
        run: npm install --only=dev

      - name: Run eslint
        run: npm run lint